"""
HPC: Train TF-GridNet from scratch for 7-source separation on Libri7Mix.

Same architecture as hpc_train_tfgridnet4.py but n_src=7 and uses the
Libri7Mix dataset layout (generated by submit_dataprep7.sh):

  $BLACKHOLE/libri7mix/
    train-360/
      mix/    <- 4-channel WAV (we average to mono)
      s1..s7/ <- mono clean sources at 16kHz
    dev/

Key differences from 4-source version:
  - n_src=7, sr=16000 (Libri7Mix is 16kHz, Libri4Mix is 8kHz)
  - STFT n_fft=512 hop=256 (32ms/16ms at 16kHz)
  - PIT over 7 sources (5040 permutations — expensive; use linear sum assignment)
  - Smaller model (d_model=48, n_blocks=4) to fit in 40GB A100 with batch_size=4

Usage:
    python hpc_train_tfgridnet7.py \\
        --train-dir $BLACKHOLE/libri7mix/train-360 \\
        --val-dir   $BLACKHOLE/libri7mix/dev \\
        --epochs 50 --batch-size 4
"""

import argparse
import glob
import os
import warnings

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from scipy.io import wavfile
from scipy.optimize import linear_sum_assignment
from scipy.signal import fftconvolve
from torch.utils.data import DataLoader, Dataset

warnings.filterwarnings("ignore")


# ── TF-GridNet (identical to 4-src version, parameterised by n_src) ───────────

class IntraFrameModule(nn.Module):
    def __init__(self, d_model: int, hidden: int):
        super().__init__()
        self.norm = nn.LayerNorm(d_model)
        self.lstm = nn.LSTM(d_model, hidden, batch_first=True, bidirectional=True)
        self.proj = nn.Linear(hidden * 2, d_model)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, D, T, F = x.shape
        r = x.permute(0, 2, 3, 1).reshape(B * T, F, D)
        r = self.norm(r)
        r, _ = self.lstm(r)
        r = self.proj(r)
        r = r.reshape(B, T, F, D).permute(0, 3, 1, 2)
        return x + r


class InterFrameModule(nn.Module):
    def __init__(self, d_model: int, hidden: int):
        super().__init__()
        self.norm = nn.LayerNorm(d_model)
        self.lstm = nn.LSTM(d_model, hidden, batch_first=True, bidirectional=True)
        self.proj = nn.Linear(hidden * 2, d_model)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, D, T, F = x.shape
        r = x.permute(0, 3, 2, 1).reshape(B * F, T, D)
        r = self.norm(r)
        r, _ = self.lstm(r)
        r = self.proj(r)
        r = r.reshape(B, F, T, D).permute(0, 3, 2, 1)
        return x + r


class TFGridNetBlock(nn.Module):
    def __init__(self, d_model: int, hidden: int):
        super().__init__()
        self.intra = IntraFrameModule(d_model, hidden)
        self.inter = InterFrameModule(d_model, hidden)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.inter(self.intra(x))


class TFGridNet(nn.Module):
    def __init__(self, n_src=7, n_fft=512, hop=256, d_model=48, hidden=128, n_blocks=4):
        super().__init__()
        self.n_src  = n_src
        self.n_fft  = n_fft
        self.hop    = hop
        self.n_bins = n_fft // 2 + 1
        self.input_proj  = nn.Conv2d(2, d_model, kernel_size=1)
        self.blocks      = nn.ModuleList([TFGridNetBlock(d_model, hidden) for _ in range(n_blocks)])
        self.output_proj = nn.Conv2d(d_model, n_src * 2, kernel_size=1)

    def forward(self, mix: torch.Tensor) -> torch.Tensor:
        window = torch.hann_window(self.n_fft, device=mix.device)
        X = torch.stft(mix, self.n_fft, self.hop, window=window,
                       return_complex=True, center=True)
        inp  = torch.stack([X.real, X.imag], dim=1)
        feat = self.input_proj(inp)
        feat = feat.permute(0, 1, 3, 2)
        for block in self.blocks:
            feat = block(feat)
        feat  = feat.permute(0, 1, 3, 2)
        masks = self.output_proj(feat)
        masks = masks.view(mix.shape[0], self.n_src, 2, self.n_bins, -1)
        sources = []
        for s in range(self.n_src):
            m_re = masks[:, s, 0]
            m_im = masks[:, s, 1]
            s_re = X.real * m_re - X.imag * m_im
            s_im = X.real * m_im + X.imag * m_re
            S = torch.complex(s_re, s_im)
            wav = torch.istft(S, self.n_fft, self.hop, window=window,
                              length=mix.shape[-1], center=True)
            sources.append(wav)
        return torch.stack(sources, dim=1)


# ── PIT SI-SNR loss (Hungarian algorithm — avoids 5040 permutations) ─────────

def si_snr(estimate: torch.Tensor, target: torch.Tensor, eps: float = 1e-8) -> torch.Tensor:
    estimate = estimate - estimate.mean(dim=-1, keepdim=True)
    target   = target   - target.mean(dim=-1, keepdim=True)
    dot      = (estimate * target).sum(dim=-1, keepdim=True)
    s_target = dot * target / (target.pow(2).sum(dim=-1, keepdim=True) + eps)
    e_noise  = estimate - s_target
    return 10 * torch.log10(
        s_target.pow(2).sum(dim=-1) / (e_noise.pow(2).sum(dim=-1) + eps) + eps
    )


def pit_si_snr_loss_hungarian(estimates: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    """PIT using Hungarian algorithm — O(n^3) instead of O(n!) for n=7."""
    B, n_src, T = targets.shape
    total_loss = 0.0
    for b in range(B):
        # Build cost matrix (n_src x n_src): negative SI-SNR
        cost = torch.zeros(n_src, n_src, device=estimates.device)
        for i in range(n_src):
            for j in range(n_src):
                cost[i, j] = -si_snr(estimates[b, i].unsqueeze(0),
                                      targets[b, j].unsqueeze(0)).squeeze()
        row, col = linear_sum_assignment(cost.detach().cpu().numpy())
        loss = cost[row, col].mean()
        total_loss += loss
    return total_loss / B


# ── Dataset ───────────────────────────────────────────────────────────────────

class Libri7MixDataset(Dataset):
    """Libri7Mix layout: mix/ (4-channel) + s1..s7/ (mono sources)."""

    def __init__(self, root: str, sr: int = 16000, max_len_s: float = 4.0):
        self.sr      = sr
        self.max_len = int(max_len_s * sr)
        self.mix_files = sorted(glob.glob(os.path.join(root, "mix", "*.wav")))
        assert len(self.mix_files) > 0, f"No WAV files found in {root}/mix/"
        print(f"  {len(self.mix_files)} mixes in {root}")

    def _load_mono(self, path: str) -> np.ndarray:
        sig, _ = __import__("soundfile").read(path, dtype="float32")
        if sig.ndim > 1:
            sig = sig.mean(axis=1)
        if len(sig) > self.max_len:
            sig = sig[:self.max_len]
        else:
            sig = np.pad(sig, (0, self.max_len - len(sig)))
        return sig

    def __len__(self) -> int:
        return len(self.mix_files)

    def __getitem__(self, idx: int):
        mix_path = self.mix_files[idx]
        stem     = os.path.basename(mix_path)
        base     = os.path.dirname(os.path.dirname(mix_path))

        mix  = self._load_mono(mix_path)
        srcs = [self._load_mono(os.path.join(base, f"s{k}", stem)) for k in range(1, 8)]

        mix_t   = torch.from_numpy(mix)
        srcs_t  = torch.from_numpy(np.stack(srcs, axis=0))   # (7, T)
        peak    = mix_t.abs().max() + 1e-8
        return mix_t / peak, srcs_t / peak


# ── Training ──────────────────────────────────────────────────────────────────

def train(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    model = TFGridNet(
        n_src=7,
        n_fft=args.n_fft,
        hop=args.hop,
        d_model=args.d_model,
        hidden=args.hidden,
        n_blocks=args.n_blocks,
    ).to(device)

    total = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Model params: {total:,} (trainable: {trainable:,})")

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", patience=5, factor=0.5, min_lr=1e-6
    )

    full_ds = Libri7MixDataset(args.train_dir, sr=args.sr, max_len_s=args.max_len_s)

    # Use separate val-dir if it exists and has data; otherwise split train 90/10
    val_dl = None
    if args.val_dir:
        val_files = glob.glob(os.path.join(args.val_dir, "mix", "*.wav"))
        if len(val_files) > 0:
            val_ds = Libri7MixDataset(args.val_dir, sr=args.sr, max_len_s=args.max_len_s)
            train_ds = full_ds
            val_dl = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False,
                                num_workers=args.num_workers, pin_memory=True, drop_last=False)
            print(f"  Using separate val dir: {len(val_files)} mixes")
        else:
            print(f"  val-dir '{args.val_dir}' is empty — falling back to 90/10 split")

    if val_dl is None:
        n_val = max(1, int(0.1 * len(full_ds)))
        n_train = len(full_ds) - n_val
        train_ds, val_ds = torch.utils.data.random_split(
            full_ds, [n_train, n_val],
            generator=torch.Generator().manual_seed(42)
        )
        val_dl = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False,
                            num_workers=args.num_workers, pin_memory=True, drop_last=False)
        print(f"  Train/val split: {n_train}/{n_val}")

    train_dl = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                          num_workers=args.num_workers, pin_memory=True, drop_last=True)

    os.makedirs(args.ckpt_dir, exist_ok=True)
    best_val = float("inf")

    for epoch in range(args.epochs):
        model.train()
        train_loss = 0.0
        for step, (mix, sources) in enumerate(train_dl):
            mix, sources = mix.to(device), sources.to(device)
            estimates    = model(mix)
            loss         = pit_si_snr_loss_hungarian(estimates, sources)
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()
            train_loss += loss.item()
            if (step + 1) % 100 == 0:
                print(f"  epoch {epoch+1} step {step+1}/{len(train_dl)}  "
                      f"loss {train_loss/(step+1):.3f}", flush=True)

        train_loss /= len(train_dl)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for mix, sources in val_dl:
                mix, sources = mix.to(device), sources.to(device)
                estimates    = model(mix)
                val_loss    += pit_si_snr_loss_hungarian(estimates, sources).item()
        val_loss /= len(val_dl)
        scheduler.step(val_loss)

        print(f"Epoch {epoch+1:3d}/{args.epochs}  "
              f"train SI-SNRi {-train_loss:.2f} dB  "
              f"val SI-SNRi {-val_loss:.2f} dB  "
              f"lr {optimizer.param_groups[0]['lr']:.2e}")

        if val_loss < best_val:
            best_val = val_loss
            ckpt = os.path.join(args.ckpt_dir, "best_model.pt")
            torch.save({"model_state": model.state_dict(), "args": vars(args),
                        "epoch": epoch, "val_si_snri": -best_val}, ckpt)
            print(f"  → Saved checkpoint  val SI-SNRi {-best_val:.2f} dB")

    print(f"\nDone. Best val SI-SNRi: {-best_val:.2f} dB")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--train-dir",   required=True)
    p.add_argument("--val-dir",     default="")
    p.add_argument("--sr",          type=int,   default=16000)
    p.add_argument("--n-fft",       type=int,   default=512)
    p.add_argument("--hop",         type=int,   default=256)
    p.add_argument("--d-model",     type=int,   default=48)
    p.add_argument("--hidden",      type=int,   default=128)
    p.add_argument("--n-blocks",    type=int,   default=4)
    p.add_argument("--epochs",      type=int,   default=50)
    p.add_argument("--batch-size",  type=int,   default=4)
    p.add_argument("--lr",          type=float, default=1e-3)
    p.add_argument("--max-len-s",   type=float, default=4.0)
    p.add_argument("--num-workers", type=int,   default=4)
    p.add_argument("--ckpt-dir",    default="analysis/dl_separation/logs/tfgridnet7_ckpt")
    args = p.parse_args()
    train(args)
