"""
HPC: Fine-tune SepFormer (3-source → 7-source) with LoRA on Libri7Mix.

Base model: speechbrain/sepformer-wsj03mix  (SI-SNRi 19.8 dB on WSJ0-3Mix)
Surgery: extend output head 3 → 7 sources (duplicating weights, then fine-tune)

LoRA is injected into all masknet attention Linear layers (default r=8).
Only ~2-5% of parameters are trained; the extended output head is fully trainable.

Input:  mono mixture (4-channel mix averaged to mono, or ch0)
Target: 7 clean mono sources

Dataset: Libri7Mix (generated by submit_dataprep7.sh)
Layout:  $BLACKHOLE/libri7mix/train-360/
           mix/    <- 4-channel WAV (we use mean as mono input)
           s1..s7/ <- mono clean sources
         $BLACKHOLE/libri7mix/dev/

Usage:
    python hpc_finetune_sepformer7.py \\
        --train-dir $BLACKHOLE/libri7mix/train-360 \\
        --val-dir   $BLACKHOLE/libri7mix/dev \\
        --epochs 30 --batch-size 8
"""

import argparse
import glob
import os
import warnings

import numpy as np
import torch
import torch.nn as nn
import soundfile as sf
from torch.utils.data import DataLoader, Dataset

warnings.filterwarnings("ignore")

from speechbrain.inference.separation import SepformerSeparation
from speechbrain.nnet.losses import get_si_snr_with_pitwrapper


N_SRC = 7


# ── LoRA (identical to sepformer4 version) ───────────────────────────────────

class LoRALinear(nn.Module):
    def __init__(self, linear: nn.Linear, r: int = 8, alpha: float = 16.0):
        super().__init__()
        self.linear = linear
        self.linear.weight.requires_grad_(False)
        if self.linear.bias is not None:
            self.linear.bias.requires_grad_(False)
        self.lora_A = nn.Parameter(torch.randn(linear.in_features, r) * 0.01)
        self.lora_B = nn.Parameter(torch.zeros(r, linear.out_features))
        self.scale  = alpha / r

    def forward(self, x):
        return self.linear(x) + (x @ self.lora_A @ self.lora_B) * self.scale


def inject_lora(module: nn.Module, r: int = 8, alpha: float = 16.0) -> int:
    n = 0
    for name, child in list(module.named_children()):
        if isinstance(child, nn.Linear):
            setattr(module, name, LoRALinear(child, r=r, alpha=alpha))
            n += 1
        else:
            n += inject_lora(child, r=r, alpha=alpha)
    return n


def freeze_non_lora(model: nn.Module):
    for name, param in model.named_parameters():
        if "lora_A" not in name and "lora_B" not in name:
            param.requires_grad_(False)


# ── Model surgery ─────────────────────────────────────────────────────────────

def extend_output_to_n_src(model: nn.Module, n_src_new: int) -> nn.Module:
    masknet = model.mods.masknet

    print("\n── SepFormer masknet output layers ──")
    for name, module in masknet.named_modules():
        if isinstance(module, (nn.Conv1d, nn.Linear)):
            out_dim = module.out_channels if isinstance(module, nn.Conv1d) else module.out_features
            print(f"  {name:60s}  {type(module).__name__}  out={out_dim}")
    print("─────────────────────────────────────\n")

    n_src_old = getattr(masknet, "num_spks", None)
    print(f"  masknet.num_spks = {n_src_old}")
    if n_src_old is None:
        n_src_old = 3  # default: wsj03mix base

    if n_src_old == n_src_new:
        print("  num_spks already matches target, no surgery needed.")
        return model

    extended = 0

    # Strategy 1: look for Conv1d where out_channels is divisible by n_src_old
    # These are source-output projections (N * n_src_old → N * n_src_new)
    for name, mod in masknet.named_modules():
        if isinstance(mod, nn.Conv1d) and mod.out_channels > n_src_old \
                and mod.out_channels % n_src_old == 0:
            N = mod.out_channels // n_src_old
            repeats = -(-n_src_new // n_src_old)
            new_w = mod.weight.data.repeat(repeats, 1, 1)[: N * n_src_new]
            mod.out_channels = N * n_src_new
            mod.weight = nn.Parameter(new_w)
            if mod.bias is not None:
                mod.bias = nn.Parameter(
                    mod.bias.data.repeat(repeats)[: N * n_src_new]
                )
            print(f"  [s1] Extended '{name}': {N * n_src_old} → {N * n_src_new}")
            extended += 1

    # Strategy 2 (fallback): find layers named 'output' and rebuild them,
    # mapping in_channels → in_channels * n_src_new (reinit, copy what we can)
    if extended == 0:
        print("  Strategy 1 found nothing. Falling back to output-name search...")
        for name, mod in masknet.named_modules():
            if "output" in name.lower() and isinstance(mod, nn.Conv1d):
                in_ch = mod.in_channels
                old_out = mod.out_channels
                new_out = in_ch * n_src_new
                new_w = torch.empty(new_out, *mod.weight.shape[1:])
                nn.init.kaiming_uniform_(new_w, a=0)
                n_copy = min(old_out, new_out)
                new_w[:n_copy] = mod.weight.data[:n_copy]
                mod.out_channels = new_out
                mod.weight = nn.Parameter(new_w)
                if mod.bias is not None:
                    new_b = torch.zeros(new_out)
                    new_b[:min(len(mod.bias.data), new_out)] = \
                        mod.bias.data[:min(len(mod.bias.data), new_out)]
                    mod.bias = nn.Parameter(new_b)
                print(f"  [s2] Rebuilt '{name}' (in={in_ch}): {old_out} → {new_out}")
                extended += 1

    if hasattr(masknet, "num_spks"):
        masknet.num_spks = n_src_new
        print(f"  Updated masknet.num_spks → {n_src_new}")

    if extended == 0:
        raise RuntimeError(
            f"Could not find any output layers to extend to {n_src_new} sources.\n"
            f"Dump of masknet: {masknet}"
        )

    print(f"  Extended {extended} layer(s) total.")
    return model


# ── Dataset ───────────────────────────────────────────────────────────────────

class Libri7MixDataset(Dataset):
    """
    Libri7Mix layout:
        root/mix/mix_XXXXXX.wav    — 4-channel reverberant mixture
        root/s1/mix_XXXXXX.wav    — mono clean source 1
        ...
        root/s7/mix_XXXXXX.wav    — mono clean source 7

    Returns:
        mix:     (T,)       — mono mixture (mean of 4 channels)
        sources: (N_SRC, T) — clean mono sources
    """

    def __init__(self, root: str, sr: int = 16000, max_len_s: float = 4.0):
        self.root    = root
        self.sr      = sr
        self.max_len = int(max_len_s * sr)
        self.mix_files = sorted(glob.glob(os.path.join(root, "mix", "*.wav")))
        assert len(self.mix_files) > 0, (
            f"No WAV files found in {root}/mix/ — check data path and run submit_dataprep7.sh first."
        )

    def _load_mono(self, path: str) -> np.ndarray:
        sig, _ = sf.read(path, dtype="float32")
        if sig.ndim > 1:
            sig = sig.mean(axis=1)
        if len(sig) > self.max_len:
            sig = sig[: self.max_len]
        else:
            sig = np.pad(sig, (0, self.max_len - len(sig)))
        return sig

    def __len__(self) -> int:
        return len(self.mix_files)

    def __getitem__(self, idx: int):
        stem = os.path.basename(self.mix_files[idx])
        # 4-channel mix → mean to mono
        mix_4ch, _ = sf.read(self.mix_files[idx], dtype="float32")
        if mix_4ch.ndim > 1:
            mix_mono = mix_4ch.mean(axis=1)
        else:
            mix_mono = mix_4ch
        if len(mix_mono) > self.max_len:
            mix_mono = mix_mono[: self.max_len]
        else:
            mix_mono = np.pad(mix_mono, (0, self.max_len - len(mix_mono)))

        srcs = np.stack([
            self._load_mono(os.path.join(self.root, f"s{k}", stem))
            for k in range(1, N_SRC + 1)
        ], axis=0)   # (N_SRC, T)

        mix_t  = torch.from_numpy(mix_mono)
        srcs_t = torch.from_numpy(srcs)
        peak   = mix_t.abs().max() + 1e-8
        return mix_t / peak, srcs_t / peak


# ── Training ──────────────────────────────────────────────────────────────────

def run_model(model_sb, mix, n_src, device):
    """Forward pass through encoder → masknet → decoder. Returns (B, n_src, T)."""
    enc   = model_sb.mods.encoder(mix.unsqueeze(1))   # (B, N, T')
    masks = model_sb.mods.masknet(enc)

    # Handle both mask layout conventions SpeechBrain may emit
    if masks.dim() == 4 and masks.shape[-1] == n_src:
        est = torch.stack(
            [model_sb.mods.decoder(enc * masks[..., s]).squeeze(1) for s in range(n_src)],
            dim=1,
        )
    elif masks.dim() == 4 and masks.shape[0] == n_src:
        est = torch.stack(
            [model_sb.mods.decoder(enc * masks[s]).squeeze(1) for s in range(n_src)],
            dim=1,
        )
    else:
        est = model_sb.mods.decoder(masks)
        if est.dim() == 2:
            est = est.unsqueeze(1)
    return est


def train(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")
    print(f"Base model: {args.base_model}  (base n_src={args.base_n_src})")

    print(f"\nLoading {args.base_model} ...")
    model_sb = SepformerSeparation.from_hparams(
        source=args.base_model,
        savedir=f"./pretrained_{args.base_model.replace('/', '_')}",
        run_opts={"device": str(device)},
    )
    assert hasattr(model_sb, "mods"),               "model_sb has no .mods"
    assert hasattr(model_sb.mods, "encoder"),       "mods has no encoder"
    assert hasattr(model_sb.mods, "masknet"),       "mods has no masknet"
    assert hasattr(model_sb.mods, "decoder"),       "mods has no decoder"

    if args.base_n_src < N_SRC:
        print(f"\nExtending output head {args.base_n_src} → {N_SRC} sources ...")
        model_sb = extend_output_to_n_src(model_sb, n_src_new=N_SRC)

    n_lora = inject_lora(model_sb.mods.masknet, r=args.lora_r, alpha=args.lora_alpha)
    print(f"Injected LoRA into {n_lora} Linear layers")
    freeze_non_lora(model_sb.mods)

    if hasattr(model_sb.mods.masknet, "output_layer"):
        for p in model_sb.mods.masknet.output_layer.parameters():
            p.requires_grad_(True)

    trainable = sum(p.numel() for p in model_sb.mods.parameters() if p.requires_grad)
    total     = sum(p.numel() for p in model_sb.mods.parameters())
    print(f"Trainable: {trainable:,} / {total:,}  ({100*trainable/total:.1f}%)")
    model_sb.mods.to(device)

    optimizer = torch.optim.AdamW(
        [p for p in model_sb.mods.parameters() if p.requires_grad],
        lr=args.lr, weight_decay=1e-4,
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)

    train_ds = Libri7MixDataset(args.train_dir, sr=args.sr, max_len_s=args.max_len_s)
    val_ds   = Libri7MixDataset(args.val_dir,   sr=args.sr, max_len_s=args.max_len_s)
    train_dl = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                          num_workers=args.num_workers, pin_memory=True)
    val_dl   = DataLoader(val_ds,   batch_size=args.batch_size, shuffle=False,
                          num_workers=args.num_workers, pin_memory=True)

    os.makedirs(args.ckpt_dir, exist_ok=True)
    best_val = float("inf")

    for epoch in range(args.epochs):
        model_sb.mods.train()
        train_loss = 0.0
        for mix, sources in train_dl:
            mix, sources = mix.to(device), sources.to(device)
            est = run_model(model_sb, mix, N_SRC, device)
            T = sources.shape[-1]
            est = est[..., :T]
            if est.shape[-1] < T:
                est = torch.nn.functional.pad(est, (0, T - est.shape[-1]))
            loss = get_si_snr_with_pitwrapper(est, sources)
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(
                [p for p in model_sb.mods.parameters() if p.requires_grad], 5.0
            )
            optimizer.step()
            train_loss += loss.item()
        train_loss /= len(train_dl)

        model_sb.mods.eval()
        val_loss = 0.0
        with torch.no_grad():
            for mix, sources in val_dl:
                mix, sources = mix.to(device), sources.to(device)
                est = run_model(model_sb, mix, N_SRC, device)
                T = sources.shape[-1]
                est = est[..., :T]
                if est.shape[-1] < T:
                    est = torch.nn.functional.pad(est, (0, T - est.shape[-1]))
                val_loss += get_si_snr_with_pitwrapper(est, sources).item()
        val_loss /= len(val_dl)
        scheduler.step()

        print(
            f"Epoch {epoch+1:3d}/{args.epochs}  "
            f"train SI-SNRi {-train_loss:.2f} dB  "
            f"val SI-SNRi {-val_loss:.2f} dB  "
            f"lr {scheduler.get_last_lr()[0]:.2e}"
        )

        if val_loss < best_val:
            best_val = val_loss
            ckpt = os.path.join(args.ckpt_dir, "best_model.pt")
            torch.save(model_sb.mods.state_dict(), ckpt)
            print(f"  → Saved checkpoint  val SI-SNRi {-best_val:.2f} dB")

    print(f"\nDone. Best val SI-SNRi: {-best_val:.2f} dB")
    print(f"Checkpoint: {os.path.abspath(args.ckpt_dir)}/best_model.pt")


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=f"Fine-tune SepFormer 3→{N_SRC} sources with LoRA")
    p.add_argument("--train-dir",   required=True)
    p.add_argument("--val-dir",     required=True)
    p.add_argument("--base-model",  default="speechbrain/sepformer-wsj03mix")
    p.add_argument("--base-n-src",  type=int,   default=3)
    p.add_argument("--sr",          type=int,   default=16000,
                   help="16 kHz to match Libri7Mix (room-simulated at 16 kHz)")
    p.add_argument("--epochs",      type=int,   default=30)
    p.add_argument("--batch-size",  type=int,   default=8,
                   help="Smaller than 4-src because 7-src PIT is heavier")
    p.add_argument("--lr",          type=float, default=3e-5)
    p.add_argument("--lora-r",      type=int,   default=8)
    p.add_argument("--lora-alpha",  type=float, default=16.0)
    p.add_argument("--max-len-s",   type=float, default=4.0)
    p.add_argument("--num-workers", type=int,   default=4)
    p.add_argument("--ckpt-dir",    default="./sepformer7_lora_checkpoint")
    args = p.parse_args()
    train(args)
