"""
HPC: Fine-tune SepFormer (3-source → 7-source) with LoRA on Libri7Mix.

Base model: speechbrain/sepformer-wsj03mix  (SI-SNRi 19.8 dB on WSJ0-3Mix)
Surgery: extend output head 3 → 7 sources (duplicating weights, then fine-tune)

LoRA is injected into all masknet attention Linear layers (default r=8).
Only ~2-5% of parameters are trained; the extended output head is fully trainable.

Input:  mono mixture (4-channel mix averaged to mono, or ch0)
Target: 7 clean mono sources

Dataset: Libri7Mix (generated by submit_dataprep7.sh)
Layout:  $BLACKHOLE/libri7mix/train-360/
           mix/    <- 4-channel WAV (we use mean as mono input)
           s1..s7/ <- mono clean sources
         $BLACKHOLE/libri7mix/dev/

Usage:
    python hpc_finetune_sepformer7.py \\
        --train-dir $BLACKHOLE/libri7mix/train-360 \\
        --val-dir   $BLACKHOLE/libri7mix/dev \\
        --epochs 30 --batch-size 8
"""

import argparse
import glob
import os
import warnings

import numpy as np
import torch
import torch.nn as nn
import soundfile as sf
from torch.utils.data import DataLoader, Dataset

warnings.filterwarnings("ignore")

from speechbrain.inference.separation import SepformerSeparation
from speechbrain.nnet.losses import get_si_snr_with_pitwrapper


N_SRC = 7


# ── LoRA (identical to sepformer4 version) ───────────────────────────────────

class LoRALinear(nn.Module):
    def __init__(self, linear: nn.Linear, r: int = 8, alpha: float = 16.0):
        super().__init__()
        self.linear = linear
        self.linear.weight.requires_grad_(False)
        if self.linear.bias is not None:
            self.linear.bias.requires_grad_(False)
        self.lora_A = nn.Parameter(torch.randn(linear.in_features, r) * 0.01)
        self.lora_B = nn.Parameter(torch.zeros(r, linear.out_features))
        self.scale  = alpha / r

    # Expose .weight / .bias so nn.MultiheadAttention can access them directly
    # (MHA bypasses .forward() and calls F.linear(x, out_proj.weight, out_proj.bias))
    @property
    def weight(self):
        return self.linear.weight

    @property
    def bias(self):
        return self.linear.bias

    def forward(self, x):
        return self.linear(x) + (x @ self.lora_A @ self.lora_B) * self.scale


def inject_lora(module: nn.Module, r: int = 8, alpha: float = 16.0) -> int:
    n = 0
    for name, child in list(module.named_children()):
        if isinstance(child, nn.Linear):
            setattr(module, name, LoRALinear(child, r=r, alpha=alpha))
            n += 1
        else:
            n += inject_lora(child, r=r, alpha=alpha)
    return n


def freeze_non_lora(model: nn.Module):
    for name, param in model.named_parameters():
        if "lora_A" not in name and "lora_B" not in name:
            param.requires_grad_(False)


# ── Model surgery ─────────────────────────────────────────────────────────────

def extend_output_to_n_src(model: nn.Module, n_src_new: int) -> nn.Module:
    """Extend SpeechBrain SepFormer (Dual_Path_Model) from n_src_old to n_src_new.

    In Dual_Path_Model the ONLY layer whose size encodes n_src is:
        self.conv2d = nn.Conv2d(N, N * num_spks, kernel_size=1)
    Everything else (output, output_gate, end_conv1x1) operates on
    [B*spks, N, L] and does not depend on num_spks in its channel count.
    We tile the conv2d weights and update masknet.num_spks.
    """
    masknet = model.mods.masknet
    n_src_old = masknet.num_spks
    print(f"  masknet.num_spks = {n_src_old}")

    if n_src_old == n_src_new:
        print("  Already at target n_src, no surgery needed.")
        return model

    # Validate conv2d exists and has the expected shape
    if not hasattr(masknet, "conv2d") or not isinstance(masknet.conv2d, nn.Conv2d):
        raise RuntimeError(
            f"Expected masknet.conv2d to be nn.Conv2d, "
            f"got {type(getattr(masknet, 'conv2d', None))}.\n"
            f"All masknet modules: {[(n, type(m).__name__) for n, m in masknet.named_modules()]}"
        )
    N          = masknet.conv2d.in_channels        # 256
    old_out    = masknet.conv2d.out_channels       # N * n_src_old = 768
    expected   = N * n_src_old
    if old_out != expected:
        raise RuntimeError(
            f"conv2d.out_channels={old_out} but expected {expected} "
            f"(N={N} * n_src_old={n_src_old}). Checkpoint mismatch."
        )

    # Tile weights: [N*n_old, N, 1, 1] → [N*n_new, N, 1, 1]
    repeats = -(-n_src_new // n_src_old)           # ceil div
    old_w   = masknet.conv2d.weight.data
    new_w   = old_w.repeat(repeats, 1, 1, 1)[: N * n_src_new]

    has_bias   = masknet.conv2d.bias is not None
    new_conv2d = nn.Conv2d(N, N * n_src_new, kernel_size=1, bias=has_bias)
    new_conv2d.weight = nn.Parameter(new_w)
    if has_bias:
        new_conv2d.bias = nn.Parameter(
            masknet.conv2d.bias.data.repeat(repeats)[: N * n_src_new]
        )

    masknet.conv2d   = new_conv2d
    masknet.num_spks = n_src_new
    print(f"  Replaced conv2d: Conv2d({N}, {old_out}) → Conv2d({N}, {N * n_src_new})")
    print(f"  Updated num_spks: {n_src_old} → {n_src_new}")
    return model


# ── Dataset ───────────────────────────────────────────────────────────────────

class Libri7MixDataset(Dataset):
    """
    Libri7Mix layout:
        root/mix/mix_XXXXXX.wav    — 4-channel reverberant mixture
        root/s1/mix_XXXXXX.wav    — mono clean source 1
        ...
        root/s7/mix_XXXXXX.wav    — mono clean source 7

    Returns:
        mix:     (T,)       — mono mixture (mean of 4 channels)
        sources: (N_SRC, T) — clean mono sources
    """

    def __init__(self, root: str, sr: int = 16000, max_len_s: float = 4.0):
        self.root    = root
        self.sr      = sr
        self.max_len = int(max_len_s * sr)
        self.mix_files = sorted(glob.glob(os.path.join(root, "mix", "*.wav")))
        assert len(self.mix_files) > 0, (
            f"No WAV files found in {root}/mix/ — check data path and run submit_dataprep7.sh first."
        )

    def _load_mono(self, path: str) -> np.ndarray:
        sig, _ = sf.read(path, dtype="float32")
        if sig.ndim > 1:
            sig = sig.mean(axis=1)
        if len(sig) > self.max_len:
            sig = sig[: self.max_len]
        else:
            sig = np.pad(sig, (0, self.max_len - len(sig)))
        return sig

    def __len__(self) -> int:
        return len(self.mix_files)

    def __getitem__(self, idx: int):
        stem = os.path.basename(self.mix_files[idx])
        # 4-channel mix → mean to mono
        mix_4ch, _ = sf.read(self.mix_files[idx], dtype="float32")
        if mix_4ch.ndim > 1:
            mix_mono = mix_4ch.mean(axis=1)
        else:
            mix_mono = mix_4ch
        if len(mix_mono) > self.max_len:
            mix_mono = mix_mono[: self.max_len]
        else:
            mix_mono = np.pad(mix_mono, (0, self.max_len - len(mix_mono)))

        srcs = np.stack([
            self._load_mono(os.path.join(self.root, f"s{k}", stem))
            for k in range(1, N_SRC + 1)
        ], axis=0)   # (N_SRC, T)

        mix_t  = torch.from_numpy(mix_mono)
        srcs_t = torch.from_numpy(srcs)
        peak   = mix_t.abs().max() + 1e-8
        return mix_t / peak, srcs_t / peak


# ── Training ──────────────────────────────────────────────────────────────────

def run_model(model_sb, mix, n_src, device):
    """Forward pass through encoder → masknet → decoder. Returns (B, n_src, T).

    SpeechBrain SepFormer shapes (verified against SB 1.1.0):
      encoder  : [B, T]          → [B, N, T']   (encoder does unsqueeze internally)
      masknet  : [B, N, T']      → [n_src, B, N, T']
      decoder  : [B, N, T']      → [B, T]
    """
    mix   = mix.reshape(mix.shape[0], -1)    # [B, T]  (guard against any extra dims)
    enc   = model_sb.mods.encoder(mix)       # [B, N, T']  — encoder handles unsqueeze
    masks = model_sb.mods.masknet(enc)       # [n_src, B, N, T']

    if not (masks.dim() == 4 and masks.shape[0] == n_src):
        raise RuntimeError(
            f"Unexpected masknet output: shape={tuple(masks.shape)}, "
            f"expected ({n_src}, B, N, T'). Surgery may have failed."
        )

    est = torch.stack(
        [model_sb.mods.decoder(enc * masks[s]) for s in range(n_src)],
        dim=1,
    )  # [B, n_src, T]
    return est


def train(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")
    print(f"Base model: {args.base_model}  (base n_src={args.base_n_src})")

    print(f"\nLoading {args.base_model} ...")
    model_sb = SepformerSeparation.from_hparams(
        source=args.base_model,
        savedir=f"./pretrained_{args.base_model.replace('/', '_')}",
        run_opts={"device": str(device)},
    )
    assert hasattr(model_sb, "mods"),               "model_sb has no .mods"
    assert hasattr(model_sb.mods, "encoder"),       "mods has no encoder"
    assert hasattr(model_sb.mods, "masknet"),       "mods has no masknet"
    assert hasattr(model_sb.mods, "decoder"),       "mods has no decoder"

    if args.base_n_src < N_SRC:
        print(f"\nExtending output head {args.base_n_src} → {N_SRC} sources ...")
        model_sb = extend_output_to_n_src(model_sb, n_src_new=N_SRC)

    n_lora = inject_lora(model_sb.mods.masknet, r=args.lora_r, alpha=args.lora_alpha)
    print(f"Injected LoRA into {n_lora} Linear layers")
    freeze_non_lora(model_sb.mods)

    # conv2d is the extended output projection — must be trainable (not caught by LoRA)
    for p in model_sb.mods.masknet.conv2d.parameters():
        p.requires_grad_(True)

    trainable = sum(p.numel() for p in model_sb.mods.parameters() if p.requires_grad)
    total     = sum(p.numel() for p in model_sb.mods.parameters())
    print(f"Trainable: {trainable:,} / {total:,}  ({100*trainable/total:.1f}%)")
    model_sb.mods.to(device)

    optimizer = torch.optim.AdamW(
        [p for p in model_sb.mods.parameters() if p.requires_grad],
        lr=args.lr, weight_decay=1e-4,
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)

    # ── Smoke test: fail fast before touching data ────────────────────────────
    print("\n── Smoke test: one forward pass + PIT loss on random tensors ──")
    model_sb.mods.train()
    _T = int(args.sr * args.max_len_s)
    _B = 2
    _sm_mix = torch.randn(_B, _T, device=device)
    _sm_mix /= _sm_mix.abs().max() + 1e-8
    _sm_src = torch.randn(_B, N_SRC, _T, device=device)
    _sm_src /= _sm_src.abs().max() + 1e-8
    try:
        _sm_est = run_model(model_sb, _sm_mix, N_SRC, device)
        print(f"  model output shape: {tuple(_sm_est.shape)}  (expected [B={_B}, N_SRC={N_SRC}, T={_T}])")
        assert _sm_est.ndim == 3, f"Expected 3D output (B,N,T), got {_sm_est.shape}"
        assert _sm_est.shape[1] == N_SRC, f"Expected {N_SRC} sources, got {_sm_est.shape[1]}"
        _sm_T = _sm_src.shape[-1]
        _sm_est = _sm_est[..., :_sm_T]
        if _sm_est.shape[-1] < _sm_T:
            _sm_est = torch.nn.functional.pad(_sm_est, (0, _sm_T - _sm_est.shape[-1]))
        # PIT loss expects [B, T, C] — permute from [B, n_src, T]
        _sm_loss = get_si_snr_with_pitwrapper(
            _sm_src.permute(0, 2, 1), _sm_est.permute(0, 2, 1)
        ).mean()
        _sm_loss.backward()
        print(f"  loss={_sm_loss.item():.3f}  backward OK")
    except Exception as _e:
        print(f"SMOKE TEST FAILED: {_e}", flush=True)
        import traceback; traceback.print_exc()
        raise SystemExit(1) from _e
    print("── Smoke test passed ──\n")
    optimizer.zero_grad()
    del _sm_mix, _sm_src, _sm_est, _sm_loss
    # ─────────────────────────────────────────────────────────────────────────

    full_ds = Libri7MixDataset(args.train_dir, sr=args.sr, max_len_s=args.max_len_s)

    val_dl = None
    if args.val_dir:
        val_files = glob.glob(os.path.join(args.val_dir, "mix", "*.wav"))
        if len(val_files) > 0:
            val_ds   = Libri7MixDataset(args.val_dir, sr=args.sr, max_len_s=args.max_len_s)
            train_ds = full_ds
            val_dl   = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False,
                                  num_workers=args.num_workers, pin_memory=True)
            print(f"  Using separate val dir: {len(val_files)} mixes")
        else:
            print(f"  val-dir '{args.val_dir}' is empty — falling back to 90/10 split")

    if val_dl is None:
        n_val    = max(1, int(0.1 * len(full_ds)))
        n_train  = len(full_ds) - n_val
        train_ds, val_ds = torch.utils.data.random_split(
            full_ds, [n_train, n_val],
            generator=torch.Generator().manual_seed(42)
        )
        val_dl = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False,
                            num_workers=args.num_workers, pin_memory=True)
        print(f"  Train/val split: {n_train}/{n_val}")

    train_dl = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                          num_workers=args.num_workers, pin_memory=True)

    os.makedirs(args.ckpt_dir, exist_ok=True)
    best_val = float("inf")

    for epoch in range(args.epochs):
        model_sb.mods.train()
        train_loss = 0.0
        for mix, sources in train_dl:
            mix, sources = mix.to(device), sources.to(device)
            est = run_model(model_sb, mix, N_SRC, device)
            T = sources.shape[-1]
            est = est[..., :T]
            if est.shape[-1] < T:
                est = torch.nn.functional.pad(est, (0, T - est.shape[-1]))
            # PIT loss expects [B, T, C]; returns [B] — take mean
            loss = get_si_snr_with_pitwrapper(
                sources.permute(0, 2, 1), est.permute(0, 2, 1)
            ).mean()
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(
                [p for p in model_sb.mods.parameters() if p.requires_grad], 5.0
            )
            optimizer.step()
            train_loss += loss.item()
        train_loss /= len(train_dl)

        model_sb.mods.eval()
        val_loss = 0.0
        with torch.no_grad():
            for mix, sources in val_dl:
                mix, sources = mix.to(device), sources.to(device)
                est = run_model(model_sb, mix, N_SRC, device)
                T = sources.shape[-1]
                est = est[..., :T]
                if est.shape[-1] < T:
                    est = torch.nn.functional.pad(est, (0, T - est.shape[-1]))
                val_loss += get_si_snr_with_pitwrapper(
                    sources.permute(0, 2, 1), est.permute(0, 2, 1)
                ).mean().item()
        val_loss /= len(val_dl)
        scheduler.step()

        print(
            f"Epoch {epoch+1:3d}/{args.epochs}  "
            f"train SI-SNRi {-train_loss:.2f} dB  "
            f"val SI-SNRi {-val_loss:.2f} dB  "
            f"lr {scheduler.get_last_lr()[0]:.2e}"
        )

        if val_loss < best_val:
            best_val = val_loss
            ckpt = os.path.join(args.ckpt_dir, "best_model.pt")
            torch.save(model_sb.mods.state_dict(), ckpt)
            print(f"  → Saved checkpoint  val SI-SNRi {-best_val:.2f} dB")

    print(f"\nDone. Best val SI-SNRi: {-best_val:.2f} dB")
    print(f"Checkpoint: {os.path.abspath(args.ckpt_dir)}/best_model.pt")


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=f"Fine-tune SepFormer 3→{N_SRC} sources with LoRA")
    p.add_argument("--train-dir",   required=True)
    p.add_argument("--val-dir",     default="")
    p.add_argument("--base-model",  default="speechbrain/sepformer-wsj03mix")
    p.add_argument("--base-n-src",  type=int,   default=3)
    p.add_argument("--sr",          type=int,   default=16000,
                   help="16 kHz to match Libri7Mix (room-simulated at 16 kHz)")
    p.add_argument("--epochs",      type=int,   default=30)
    p.add_argument("--batch-size",  type=int,   default=8,
                   help="Smaller than 4-src because 7-src PIT is heavier")
    p.add_argument("--lr",          type=float, default=3e-5)
    p.add_argument("--lora-r",      type=int,   default=8)
    p.add_argument("--lora-alpha",  type=float, default=16.0)
    p.add_argument("--max-len-s",   type=float, default=4.0)
    p.add_argument("--num-workers", type=int,   default=4)
    p.add_argument("--ckpt-dir",    default="./sepformer7_lora_checkpoint")
    args = p.parse_args()
    train(args)
